### ISSUE TITLE
Recognition results not showing

### ISSUE THREAD

**Issue by paddyow** [Kademi/kademi-public#155]
This user https://adminupdates.admin.kademi-qa.co/manageUsers/34328582/#summary-tab
This page http://test-adminupdates.kademi-qa.co/results3.html
This topic https://adminupdates.admin.kademi-qa.co/recognition/34325484/

Leaderboard results not showing
Past period data not showing

![image](https://user-images.githubusercontent.com/2201340/114332841-5479e980-9b8a-11eb-9cda-0f6563f2efb1.png)

**Comment by bradmac** [comment]
FYI, I clicked "show logs" on the publish job:
https://adminupdates.admin.kademi-qa.co/tasks/?jobId=34414126&showLogs

![image](https://user-images.githubusercontent.com/826458/114333939-a11af000-9b9d-11eb-8764-32329a8b4ac3.png)

**Comment by bradmac** [comment]
![image](https://user-images.githubusercontent.com/826458/114334004-cad41700-9b9d-11eb-89b2-b995da34bc5a.png)

**Comment by bradmac** [comment]
You can easily see this by checking the participants
![image](https://user-images.githubusercontent.com/826458/114334072-e7704f00-9b9d-11eb-91ec-39b2605c862e.png)
![image](https://user-images.githubusercontent.com/826458/114334084-ee975d00-9b9d-11eb-990a-b42aa74baf5f.png)

The 3 users in the results are shown because they were previously included. If you click delete all then regenerate you'll see that they are gone
